cf:
  butlers:
    pws: cf-butler-talkative-chimpanzee.cfapps.io
  sslValidationSkipped: true

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,scheduledtasks,loggers,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

spring:
  cloud:
    config:
      enabled: false

---
spring:
  profiles: cloud

  cloud:
    config:
      enabled: true
